version: 2.1
#############################################################
# Shared jobs and configuration
#############################################################
attach_workspace: &attach_workspace
  attach_workspace:
    at: '.'
#############################################################
# Define workflows
#############################################################

workflows:
  build:
    jobs:
      - llpa_buildTest
jobs:
  llpa_buildTest:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:3.1
  
    steps:
      - *attach_workspace
      
      - run:
          name: Run Tests
          command: |     
            
            dotnet test 
